blank_issues_enabled: false
contact_links:
  - name: AstroPaper Discussions
    url: https://github.com/0xumarkhatab/0xumarkhatab.github.io/discussions
    about: Please ask and answer questions here.
